[build]
target-dir = "target"

[alias]
# Development shortcuts
dev = "run --bin cds-index-service"
cli = "run --bin cds"
test-all = "test --all --lib --bins --tests"
bench-all = "bench --all"
check-all = "check --all --all-targets"

# Linting
fmt-check = "fmt --all -- --check"
clippy-strict = "clippy --all-targets --all-features -- -D warnings"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
